In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [5]:
data = pd.read_csv("iris.csv");


print(data.head());

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [8]:
X = data[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]];

y = data["Species"];

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42);

In [11]:
scalar = StandardScaler();
X_train_scaled = scalar.fit_transform(X_train);
X_test_scaled = scalar.fit_transform(X_test);

In [12]:
dtModel = DecisionTreeClassifier(criterion="entropy", random_state=42);
knnModel = KNeighborsClassifier(n_neighbors=5);

In [13]:
dtModel.fit(X_train, y_train);
knnModel.fit(X_train_scaled, y_train);

In [14]:
predDt = dtModel.predict(X_test);
predKnn = knnModel.predict(X_test_scaled);

In [15]:
print("Decision tree reult: ");
print("Accurancy:", round(accuracy_score(y_test, predDt)*100, 2), "%");
print(confusion_matrix(y_test, predDt));
print(classification_report(y_test, predDt));

Decision tree reult: 
Accurancy: 100.0 %
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [17]:
print("KNN tree reult: ");
print("Accurancy:", round(accuracy_score(y_test, predKnn)*100, 2), "%");
print(confusion_matrix(y_test, predKnn));
print(classification_report(y_test, predKnn));

KNN tree reult: 
Accurancy: 96.67 %
[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

